const RestaurantData = [
  {
    id: 1,
    name: "Green Spoon Veg Delight",
    phone: "9876543210",
    address: "123, Green Valley Road, Dharampeth, Nagpur - 440010",
    status: "Rejected",
    foodType: "Veg",
    description:
      "A clean and cozy vegetarian restaurant offering homemade-style meals. Known for its hygiene and quick service, popular among college students and families.",
    priceDay: 300,
    priceWeekly: 2000,
    priceMonthly: 8000,
    offer: 10,
    startTime: "07:00 AM",
    endTime: "10:00 PM",
    orderType: "Dining, Delivery",
    mealPreference: "Breakfast, Lunch, Dinner",
    mealRanges: {
      breakfast: { start: "07:00 AM", end: "09:00 AM" },
      lunch: { start: "12:00 PM", end: "02:00 PM" },
      dinner: { start: "07:00 PM", end: "10:00 PM" },
    },
    deliveryTiming: {
      breakfast: { start: "07:15 AM", end: "08:30 AM" },
      lunch: { start: "12:15 PM", end: "01:45 PM" },
      dinner: { start: "07:15 PM", end: "08:45 PM" },
    },
    includes: [
      "Thali with 2 Sabzis",
      "Dal & Rice",
      "Roti/Chapati",
      "Pickle & Salad",
      "Sweet Dish (once a week)",
    ],
  },
  {
    id: 2,
    name: "City Bites Multi-Cuisine",
    phone: "9123456789",
    address: "45, Rosewood Lane, Ramdaspeth, Nagpur - 440012",
    status: "Approved",
    foodType: "Veg, Non-Veg",
    description:
      "Multi-cuisine family restaurant offering Indian, Chinese, and Tandoor dishes. Dine-in and quick delivery available within city limits.",
    priceDay: 350,
    priceWeekly: 2400,
    priceMonthly: 8800,
    offer: 15,
    startTime: "09:00 AM",
    endTime: "11:00 PM",
    orderType: "Dining, Delivery",
    mealPreference: "Lunch, Dinner",
    mealRanges: {
      breakfast: { start: "09:00 AM", end: "10:00 AM" },
      lunch: { start: "12:30 PM", end: "02:30 PM" },
      dinner: { start: "08:00 PM", end: "11:00 PM" },
    },
    deliveryTiming: {
      lunch: { start: "01:00 PM", end: "02:00 PM" },
      dinner: { start: "08:00 PM", end: "10:00 PM" },
    },
    includes: [
      "Butter Chicken / Paneer Butter Masala",
      "Naan / Roti",
      "Biryani",
      "Raita",
      "Soft Drink (optional)",
    ],
  },
  {
    id: 3,
    name: "Healthy Bites Cafe",
    phone: "9812345670",
    address: "78, Lake View Society, Pratap Nagar, Nagpur - 440015",
    status: "Pending",
    foodType: "Veg",
    description:
      "A health-focused cafe serving low-oil, low-sugar vegetarian meals with fresh ingredients. Ideal for fitness enthusiasts and health-conscious eaters.",
    priceDay: 280,
    priceWeekly: 1800,
    priceMonthly: 7500,
    offer: 5,
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    orderType: "Delivery Only",
    mealPreference: "Breakfast, Lunch",
    mealRanges: {
      breakfast: { start: "10:00 AM", end: "11:00 AM" },
      lunch: { start: "11:30 AM", end: "12:00 PM" },
      dinner: { start: "12:00 PM", end: "12:00 PM" }, // dinner outside hours
    },
    deliveryTiming: {
      breakfast: { start: "10:15 AM", end: "10:45 AM" },
      lunch: { start: "11:30 AM", end: "12:00 PM" },
    },
    includes: [
      "Oats Upma",
      "Sprout Salad",
      "Grilled Sandwich",
      "Fruit Bowl",
      "Detox Juice",
    ],
  },
  {
    id: 4,
    name: "The Spice Lounge",
    phone: "9988776655",
    address: "201, Shankar Nagar, Hingna Road, Nagpur - 440016",
    status: "Approved",
    foodType: "Non-Veg",
    description:
      "Premium non-veg dining with classic Indian and Mughlai dishes. Elegant ambience for dine-in and quick delivery options.",
    priceDay: 420,
    priceWeekly: 2700,
    priceMonthly: 9500,
    offer: 12,
    startTime: "07:00 AM",
    endTime: "10:00 PM",
    orderType: "Dining, Delivery",
    mealPreference: "Dinner",
    mealRanges: {
      breakfast: { start: "07:00 AM", end: "09:00 AM" },
      lunch: { start: "12:30 PM", end: "02:00 PM" },
      dinner: { start: "07:00 PM", end: "10:00 PM" },
    },
    deliveryTiming: {
      dinner: { start: "07:00 PM", end: "10:00 PM" },
    },
    includes: [
      "Mutton Rogan Josh",
      "Chicken Biryani",
      "Butter Naan",
      "Gulab Jamun",
      "Mineral Water",
    ],
  },
  {
    id: 5,
    name: "Budget Tiffins",
    phone: "9090909090",
    address: "5, Lotus Apartments, Trimurti Nagar, Nagpur - 440022",
    status: "Rejected",
    foodType: "Veg",
    description:
      "Affordable tiffin service for students and working professionals. Home-cooked food delivered fresh daily.",
    priceDay: 220,
    priceWeekly: 1400,
    priceMonthly: 6000,
    offer: 18,
    startTime: "09:00 AM",
    endTime: "10:30 PM",
    orderType: "Delivery",
    mealPreference: "Lunch",
    mealRanges: {
      breakfast: { start: "09:00 AM", end: "09:30 AM" },
      lunch: { start: "12:00 PM", end: "02:00 PM" },
      dinner: { start: "08:00 PM", end: "10:30 PM" },
    },
    deliveryTiming: {
      lunch: { start: "12:00 PM", end: "02:00 PM" },
    },
    includes: ["Rice", "Chapati (4)", "Dal / Curry", "Dry Veg", "Pickle"],
  },
  {
    id: 6,
    name: "Office Meals by Aspire",
    phone: "9876512345",
    address: "12, Tech Park Road, IT Hub, Nagpur - 440024",
    status: "Approved",
    foodType: "Veg, Non-Veg",
    description:
      "Corporate lunch provider with customizable weekly plans. Ideal for office lunches with scheduled delivery.",
    priceDay: 380,
    priceWeekly: 2250,
    priceMonthly: 8200,
    offer: 10,
    startTime: "08:00 AM",
    endTime: "12:00 PM",
    orderType: "Delivery",
    mealPreference: "Lunch",
    mealRanges: {
      breakfast: { start: "08:00 AM", end: "09:00 AM" },
      lunch: { start: "12:00 PM", end: "12:30 PM" },
      dinner: { start: "12:00 PM", end: "12:00 PM" },
    },
    deliveryTiming: {
      lunch: { start: "12:00 PM", end: "12:30 PM" },
    },
    includes: [
      "Paneer / Chicken Gravy",
      "Rice / Pulao",
      "Chapati",
      "Curd",
      "Fruit / Sweet",
    ],
  },
];

export default RestaurantData;
